print("Hi Raisha, How are you?")
status = input("")
print(f"ok. I understand. You are {status}")
location =  input("Where is your father now?")
print(f"O, you father is in {location} now. Grate. 🤡🙂G")
